platform :ios, '12.0'

target 'Liste' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Hero'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'  
  pod 'FirebaseFirestoreSwift'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.1.10-beta.0'

end
