platform :ios, '12.0'

target 'Liste' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Hero'
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'  
  pod 'FirebaseFirestoreSwift'

end
